init:
  - "SET PATH=C:\\Python27\\Scripts;%PATH%"
  - "ECHO PATH=%PATH%"
  - python --version

build: off

install:
  - pip install -U pip
  - pip install tox

test_script:
  - tox -e isort-check,py27,py34,py35,py36,py37
